export const CLIENT_EVENTS = {
  ROOM_CREATE: 'room:create',
  ROOM_JOIN: 'room:join',
  ROOM_RECONNECT: 'room:reconnect',
  ROOM_CLOSE: 'room:close',
  QUIZ_END: 'quiz:end',
  QUIZ_QUESTIONS_SET: 'quiz:questions:set',
  QUIZ_START: 'quiz:start',
  QUESTION_OPEN: 'question:open',
  QUESTION_LOCK: 'question:lock',
  QUESTION_UNLOCK: 'question:unlock',
  ROUND_LOCK: 'round:lock',
  ANSWER_SUBMIT: 'answer:submit',
  ANSWER_UPDATE: 'answer:update',
  GAME_START: 'game:start',
  GAME_SUBMIT: 'game:submit',
  REVEAL_IMAGE_TILE: 'revealImage:tile',
  REVEAL_IMAGE_SHOW_CHOICES: 'revealImage:showChoices',
  GRADING_START: 'grading:start',
  GRADING_END: 'grading:end',
  OPEN_ANSWER_GRADING_MODE_SET: 'settings:openAnswerGradingMode',
  SETTINGS_SCORING_MODE_SET: 'settings:scoringMode',
  AI_GRADING_START: 'aiGrading:start',
  PEER_GRADE_SUBMIT: 'peerGrade:submit',
  PROTEST_SUBMIT: 'protest:submit',
  PROTEST_RESOLVE: 'protest:resolve',
  SCORE_OVERRIDE: 'score:override',
  LEADERBOARD_TOGGLE: 'leaderboard:toggle',
  FINAL_RESULT_LOCK: 'finalResult:lock',
  FINAL_RESULT_UNLOCK: 'finalResult:unlock',
  TEAM_REVIEW_TOGGLE: 'teamReview:toggle',
  ANSWER_KEY_TOGGLE: 'answerKey:toggle',
  TEAM_JOIN_TOGGLE: 'teamJoin:toggle',
  TEAM_REMOVE: 'team:remove',
  TEST_SESSION_START: 'testSession:start',
  TEST_SESSION_END: 'testSession:end',
  QUIZ_SCHEDULE_SET: 'quiz:schedule:set',
  QUIZ_SCHEDULE_CANCEL: 'quiz:schedule:cancel',
  QUESTION_FORCE_REOPEN: 'question:force-reopen',
} as const;

export const SERVER_EVENTS = {
  ROOM_CREATED: 'room:created',
  ROOM_JOINED: 'room:joined',
  ROOM_STATE: 'room:state',
  ERROR: 'error',
} as const;

export const MAX_TEAMS = 30;
export const DEFAULT_MAX_POINTS = 1;
